package me.freo.payment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-06-01T09:42:56.590+01:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://freo.me/payment/", name = "payment")
@XmlSeeAlso({ObjectFactory.class})
public interface Payment {

    @WebMethod(action = "http://freo.me/payment/authorise")
    @RequestWrapper(localName = "authorise", targetNamespace = "http://freo.me/payment/", className = "me.freo.payment.Authorise")
    @ResponseWrapper(localName = "authoriseResponse", targetNamespace = "http://freo.me/payment/", className = "me.freo.payment.AuthoriseResponse")
    public void authorise(
        @WebParam(name = "card", targetNamespace = "")
        me.freo.payment.CardType card,
        @WebParam(name = "merchant", targetNamespace = "")
        int merchant,
        @WebParam(mode = WebParam.Mode.INOUT, name = "reference", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> reference,
        @WebParam(name = "amount", targetNamespace = "")
        double amount,
        @WebParam(mode = WebParam.Mode.OUT, name = "authcode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> authcode,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultcode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultcode,
        @WebParam(mode = WebParam.Mode.OUT, name = "refusalreason", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> refusalreason
    );
}
