package me.freo.payment;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-06-01T09:42:56.601+01:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "payment", 
                  wsdlLocation = "./payment.wsdl",
                  targetNamespace = "http://freo.me/payment/") 
public class Payment_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://freo.me/payment/", "payment");
    public final static QName PaymentSOAP = new QName("http://freo.me/payment/", "paymentSOAP");
    static {
        URL url = Payment_Service.class.getResource("./payment.wsdl");
        if (url == null) {
            url = Payment_Service.class.getClassLoader().getResource("./payment.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(Payment_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "./payment.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public Payment_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Payment_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Payment_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Payment_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Payment_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Payment_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Payment
     */
    @WebEndpoint(name = "paymentSOAP")
    public Payment getPaymentSOAP() {
        return super.getPort(PaymentSOAP, Payment.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Payment
     */
    @WebEndpoint(name = "paymentSOAP")
    public Payment getPaymentSOAP(WebServiceFeature... features) {
        return super.getPort(PaymentSOAP, Payment.class, features);
    }

}
