# supports version 2 of the docker compose language. 
# Requires docker compose 1.6 or later
version: '2'

services:
  esb:
    image: pizak/payesb
    ports:
     - "9444:9444"
     - "8001:8281"
     - "8443:8443"
    links:
     - "pay:pay"
    depends_on:
     - pay
  pay:
    image: pizak/pay
  node:
    image: pizak/fakepay
    ports:
     - "8002:8002"
     
